name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: ${{ matrix.command }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          - "++2.12.16 ++2.11.12 semanticdbTests/test"
          - "++2.12.16 ++2.11.12 testsJVM/test"
          - "++2.12.16 ++2.12.10 semanticdbTests/test"
          - "++2.12.16 ++2.12.11 semanticdbTests/test"
          - "++2.12.16 ++2.12.12 semanticdbTests/test"
          - "++2.12.16 ++2.12.13 semanticdbTests/test"
          - "++2.12.16 ++2.12.14 semanticdbTests/test"
          - "++2.12.16 ++2.12.15 semanticdbTests/test"
          - "++2.12.16 semanticdbTests/test"
          - "++2.12.16 testsJVM/test"
          - "++2.12.16 testsJS/test"
          - "++2.12.16 testsNative/test"
          - "++2.13.1 semanticdbTests/test"
          - "++2.13.2 semanticdbTests/test"
          - "++2.13.3 semanticdbTests/test"
          - "++2.13.4 semanticdbTests/test"
          - "++2.13.5 semanticdbTests/test"
          - "++2.13.6 semanticdbTests/test"
          - "++2.13.7 semanticdbTests/test"
          - "++2.13.8 semanticdbTests/test"
          - "++2.13.8 testsJVM/test"
          - "++2.13.8 testsJS/test"
          - "++2.13.8 testsNative/test"
          - "++2.13.8 download-scala-library testsJVM/slow:test"
          - "communitytest/test"
          - "mima"
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
      - run: git fetch --unshallow
      - run: sbt ${{ matrix.command }}
  jdk11:
    name: JDK11 tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11
      - run: sbt ++2.13.8 testsJVM/test
      - run: sbt ++2.13.8 semanticdbTests/test
  windows:
    name: Windows tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
      - run: sbtx ci-windows
        shell: bash
      - run: sbtx test-semanticdb
        shell: bash
  checks:
    name: Scalafmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
      - run: ./bin/scalafmt --test
